/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[AuthUser]
(
[AuthUserId] [int] NOT NULL,
[UserName] [varchar] (100) NULL,
[NationalNumber] [char] (10) NULL,
[Email] [nvarchar] (40) NULL,
[Mobile] [varchar] (13) NULL,
[FirstName] [nvarchar] (100) NULL,
[LastName] [nvarchar] (100) NULL,
[GenderId] [tinyint] NULL,
[Birthdate] [date] NULL,
[AddressProvinceId] [int] NULL,
[AddressStreet] [nvarchar] (max) NULL,
[AddressPostalCode] [char] (10) NULL,
[IsEnabled] [bit] NOT NULL CONSTRAINT [DF_AuthUser_IsEnabled] DEFAULT ((1)),
[Description] [nvarchar] (max) NULL,
[RecordVersion] [varbinary] (8) NOT NULL,
[CreatedByUserId] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_AuthUser_CreatedTime] DEFAULT (getdate()),
[ModifiedByUserId] [int] NULL,
[ModifiedTime] [datetime] NULL,
[AddressDistrictId] [int] NULL
)
GO
ALTER TABLE [dbo].[AuthUser] ADD CONSTRAINT [PK_AuthUser] PRIMARY KEY CLUSTERED  ([AuthUserId])
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Mobile] ON [dbo].[AuthUser] ([Mobile]) WHERE ([Mobile] IS NOT NULL)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_NationalNumber] ON [dbo].[AuthUser] ([NationalNumber]) WHERE ([NationalNumber] IS NOT NULL)
GO
ALTER TABLE [dbo].[AuthUser] ADD CONSTRAINT [FK_AuthUser_Users_CreatedByUserId] FOREIGN KEY ([CreatedByUserId]) REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[AuthUser] ADD CONSTRAINT [FK_AuthUser_Users_ModifiedByUserId] FOREIGN KEY ([ModifiedByUserId]) REFERENCES [dbo].[Users] ([UserId])
GO
