/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Logs]
(
[LogId] [bigint] NOT NULL IDENTITY(1, 1),
[ApplicationId] [int] NOT NULL,
[CategoryId] [int] NULL,
[SubCategoryId] [bigint] NULL,
[CustomData] [nvarchar] (max) NULL,
[CreatedByUserId] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL
)
GO
ALTER TABLE [dbo].[Logs] ADD CONSTRAINT [PK_Logs] PRIMARY KEY CLUSTERED  ([LogId])
GO
ALTER TABLE [dbo].[Logs] ADD CONSTRAINT [FK_Logs_Applicatoins_ApplicationId] FOREIGN KEY ([ApplicationId]) REFERENCES [dbo].[Application] ([ApplicationId])
GO
