/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Setting]
(
[SettingId] [int] NOT NULL CONSTRAINT [DF_Setting_SettingId] DEFAULT ((1)),
[AppSetting1] [int] NOT NULL CONSTRAINT [DF_Setting_AppSetting1] DEFAULT ((0)),
[AppSetting2] [int] NOT NULL CONSTRAINT [DF_Setting_AppSetting2] DEFAULT ((0))
)
GO
ALTER TABLE [dbo].[Setting] ADD CONSTRAINT [PK_Setting] PRIMARY KEY CLUSTERED  ([SettingId])
GO
