/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[AppVersion]
(
[AppVersionId] [int] NOT NULL IDENTITY(1, 1),
[VersionNumber] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_AppVersion_CreatedTime] DEFAULT (getdate()),
[StartTime] [datetime2] NOT NULL CONSTRAINT [DF__AppVersio__Start__2421696F] DEFAULT (getutcdate()),
[EndTime] [datetime2] NOT NULL CONSTRAINT [DF__AppVersio__EndTi__25158DA8] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[VersioningStartTime] [datetime2] NOT NULL CONSTRAINT [DF__AppVersio__Versi__13674C79] DEFAULT (getutcdate()),
[VersioningEndTime] [datetime2] NOT NULL CONSTRAINT [DF__AppVersio__Versi__145B70B2] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0)))
)
GO
ALTER TABLE [dsp].[AppVersion] ADD CONSTRAINT [PK_AppVersion] PRIMARY KEY CLUSTERED  ([AppVersionId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'117', 'SCHEMA', N'dsp', 'TABLE', N'AppVersion', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'3', 'SCHEMA', N'dsp', 'TABLE', N'AppVersion', NULL, NULL
GO
