/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[AuthUser]
(
[AuthUserId] [int] NULL,
[UserId] [int] NOT NULL,
[StartTime] [datetime2] NOT NULL CONSTRAINT [DF__AuthUser__StartT__42F26B57] DEFAULT (getdate()),
[EndTime] [datetime2] NOT NULL CONSTRAINT [DF__AuthUser__EndTim__43E68F90] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0))),
[VersioningStartTime] [datetime2] NOT NULL CONSTRAINT [DF__AuthUser__Versio__0A6EE669] DEFAULT (getdate()),
[VersioningEndTime] [datetime2] NOT NULL CONSTRAINT [DF__AuthUser__Versio__0B630AA2] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0)))
)
GO
ALTER TABLE [dsp].[AuthUser] ADD CONSTRAINT [PK_AuthUser] PRIMARY KEY CLUSTERED  ([UserId])
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'2', 'SCHEMA', N'dsp', 'TABLE', N'AuthUser', NULL, NULL
GO
