/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[AuthUserHistory]
(
[AuthUserId] [int] NULL,
[UserId] [int] NOT NULL,
[StartTime] [datetime2] NOT NULL,
[EndTime] [datetime2] NOT NULL,
[VersioningStartTime] [datetime2] NOT NULL,
[VersioningEndTime] [datetime2] NOT NULL
)
GO
CREATE CLUSTERED INDEX [ix_AuthUserHistory] ON [dsp].[AuthUserHistory] ([VersioningEndTime], [VersioningStartTime])
GO
