/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[Exception]
(
[ExceptionId] [int] NOT NULL,
[ExceptionName] [nvarchar] (100) NOT NULL,
[StringId] [nvarchar] (100) NULL,
[Description] [nvarchar] (max) NULL
)
GO
ALTER TABLE [dsp].[Exception] ADD CONSTRAINT [PK_Exception] PRIMARY KEY CLUSTERED  ([ExceptionId])
GO
ALTER TABLE [dsp].[Exception] ADD CONSTRAINT [FK_Exception_StringTable_StringId] FOREIGN KEY ([StringId]) REFERENCES [dsp].[StringTable] ([StringId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'129', 'SCHEMA', N'dsp', 'TABLE', N'Exception', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dsp', 'TABLE', N'Exception', NULL, NULL
GO
