/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[LogFilterSetting]
(
[LogFilterSettingId] [int] NOT NULL IDENTITY(1, 1),
[UserName] [nvarchar] (100) NOT NULL,
[IsExludedFilter] [bit] NOT NULL CONSTRAINT [DF_LogFilter_IsExludedFilter] DEFAULT ((0)),
[Log_Filter] [nvarchar] (2000) NULL
)
GO
ALTER TABLE [dsp].[LogFilterSetting] ADD CONSTRAINT [PK__LogFilte__7B08B2A3AD695576] PRIMARY KEY CLUSTERED  ([LogFilterSettingId])
GO
ALTER TABLE [dsp].[LogFilterSetting] ADD CONSTRAINT [FK__LogFilter__UserN__1D13DFA0] FOREIGN KEY ([UserName]) REFERENCES [dsp].[LogUser] ([UserName])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'123', 'SCHEMA', N'dsp', 'TABLE', N'LogFilterSetting', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dsp', 'TABLE', N'LogFilterSetting', NULL, NULL
GO
