/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[LogUser]
(
[UserName] [nvarchar] (100) NOT NULL,
[IsEnabled] [bit] NOT NULL CONSTRAINT [DF_LogUser_IsEnabled] DEFAULT ((0))
)
GO
ALTER TABLE [dsp].[LogUser] ADD CONSTRAINT [PK__LogUser__C9F28457D1B75C41] PRIMARY KEY CLUSTERED  ([UserName])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'124', 'SCHEMA', N'dsp', 'TABLE', N'LogUser', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dsp', 'TABLE', N'LogUser', NULL, NULL
GO
