/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dsp].[SystemTable]
(
[SystemTableId] [int] NOT NULL,
[SchemaName] [nvarchar] (50) NOT NULL,
[TableName] [nvarchar] (400) NOT NULL,
[IsTemporal] [bit] NOT NULL CONSTRAINT [DF_SystemTable_IsTemporal] DEFAULT ((0)),
[TemporalTypeId] [tinyint] NULL,
[LevelPriority] [smallint] NULL,
[ClusterColumnsName] [nvarchar] (1000) NULL,
[IsHistoryTable] [bit] NULL
)
GO
ALTER TABLE [dsp].[SystemTable] ADD CONSTRAINT [PK__SystemTableId] PRIMARY KEY CLUSTERED  ([SystemTableId])
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_LevelPriority] ON [dsp].[SystemTable] ([LevelPriority]) WHERE ([LevelPriority] IS NOT NULL)
GO
ALTER TABLE [dsp].[SystemTable] ADD CONSTRAINT [IX_SystemTable_TableNameSchemaName] UNIQUE NONCLUSTERED  ([SchemaName], [TableName])
GO
ALTER TABLE [dsp].[SystemTable] ADD CONSTRAINT [FK_SystemTable_TemporalType] FOREIGN KEY ([TemporalTypeId]) REFERENCES [DatabaseVersioning].[TemporalType] ([TemporalTypeId])
GO
EXEC sp_addextendedproperty N'MS_Description', N'same as object_id', 'SCHEMA', N'dsp', 'TABLE', N'SystemTable', 'COLUMN', N'SystemTableId'
GO
