/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[ObjectType]
(
[ObjectTypeId] [smallint] NOT NULL,
[ObjectTypeName] [nvarchar] (100) NOT NULL
)
GO
ALTER TABLE [dspAuth].[ObjectType] ADD CONSTRAINT [PK_ObjectType] PRIMARY KEY CLUSTERED  ([ObjectTypeId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'125', 'SCHEMA', N'dspAuth', 'TABLE', N'ObjectType', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'ObjectType', NULL, NULL
GO
