/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[Permission]
(
[PermissionId] [smallint] NOT NULL,
[PermissionName] [varchar] (100) NOT NULL,
[Description] [nvarchar] (max) NULL
)
GO
ALTER TABLE [dspAuth].[Permission] ADD CONSTRAINT [PK_Permission] PRIMARY KEY CLUSTERED  ([PermissionId])
GO
ALTER TABLE [dspAuth].[Permission] ADD CONSTRAINT [IX_PermissionName] UNIQUE NONCLUSTERED  ([PermissionName])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'127', 'SCHEMA', N'dspAuth', 'TABLE', N'Permission', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'Permission', NULL, NULL
GO
