/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[PermissionGroupPermission]
(
[PermissionGroupId] [smallint] NOT NULL,
[PermissionId] [smallint] NOT NULL
)
GO
ALTER TABLE [dspAuth].[PermissionGroupPermission] ADD CONSTRAINT [PK_PermissionGroupPermission] PRIMARY KEY CLUSTERED  ([PermissionGroupId], [PermissionId])
GO
ALTER TABLE [dspAuth].[PermissionGroupPermission] ADD CONSTRAINT [FK_PermissionGroupPermission_Permission_PermissionId] FOREIGN KEY ([PermissionId]) REFERENCES [dspAuth].[Permission] ([PermissionId]) ON DELETE CASCADE
GO
ALTER TABLE [dspAuth].[PermissionGroupPermission] ADD CONSTRAINT [FK_PermissionGroupPermission_PermissionGroupId] FOREIGN KEY ([PermissionGroupId]) REFERENCES [dspAuth].[PermissionGroup] ([PermissionGroupId]) ON DELETE CASCADE
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'138', 'SCHEMA', N'dspAuth', 'TABLE', N'PermissionGroupPermission', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'PermissionGroupPermission', NULL, NULL
GO
