/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[Role]
(
[RoleId] [int] NOT NULL IDENTITY(1, 1),
[RoleName] [nvarchar] (100) NOT NULL,
[OwnerSecurityDescriptorId] [bigint] NOT NULL,
[ModifiedByUserId] [int] NOT NULL,
[RoleTypeId] [int] NULL,
[IsSystem] [bit] NOT NULL CONSTRAINT [DF_Role_IsSystem] DEFAULT ((0)),
[StartTime] [datetime2] NOT NULL CONSTRAINT [DF__Role__StartTime__62F12DE2] DEFAULT (getutcdate()),
[EndTime] [datetime2] NOT NULL CONSTRAINT [DF__Role__EndTime__63E5521B] DEFAULT (CONVERT([datetime2],'9999-12-31 23:59:59.9999999',(0)))
)
GO
ALTER TABLE [dspAuth].[Role] ADD CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED  ([RoleId])
GO
CREATE NONCLUSTERED INDEX [IX_OwnerSecurityDescriptorId] ON [dspAuth].[Role] ([OwnerSecurityDescriptorId])
GO
ALTER TABLE [dspAuth].[Role] ADD CONSTRAINT [FK_Role_OwnerSecurityDescriptorId_SecurityDescriptor] FOREIGN KEY ([OwnerSecurityDescriptorId]) REFERENCES [dspAuth].[SecurityDescriptor] ([SecurityDescriptorId])
GO
ALTER TABLE [dspAuth].[Role] ADD CONSTRAINT [FK_Role_OwnerSecurityDescriptorId_SecurityDescriptorId] FOREIGN KEY ([OwnerSecurityDescriptorId]) REFERENCES [dspAuth].[SecurityDescriptor] ([SecurityDescriptorId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'144', 'SCHEMA', N'dspAuth', 'TABLE', N'Role', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'Role', NULL, NULL
GO
