/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[RoleUser]
(
[RoleId] [int] NOT NULL,
[UserId] [int] NOT NULL,
[ModifiedByUserId] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_RoleUserMember_CreatedTime] DEFAULT (getdate())
)
GO
ALTER TABLE [dspAuth].[RoleUser] ADD CONSTRAINT [PK_RoleUserMember] PRIMARY KEY CLUSTERED  ([RoleId], [UserId])
GO
CREATE NONCLUSTERED INDEX [IX_MemberUserId] ON [dspAuth].[RoleUser] ([UserId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'146', 'SCHEMA', N'dspAuth', 'TABLE', N'RoleUser', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'RoleUser', NULL, NULL
GO
