/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[SecurityDescriptorParent]
(
[SecurityDescriptorId] [bigint] NOT NULL,
[ParentSecurityDescriptorId] [bigint] NOT NULL
)
GO
ALTER TABLE [dspAuth].[SecurityDescriptorParent] ADD CONSTRAINT [PK_SecurityDescriptorInheritance] PRIMARY KEY CLUSTERED  ([SecurityDescriptorId], [ParentSecurityDescriptorId])
GO
CREATE NONCLUSTERED INDEX [IX_SecurityDescriptorId] ON [dspAuth].[SecurityDescriptorParent] ([SecurityDescriptorId]) INCLUDE ([ParentSecurityDescriptorId])
GO
ALTER TABLE [dspAuth].[SecurityDescriptorParent] ADD CONSTRAINT [FK_SecurityDescriptorInheritance_SecurityDescriptor_ParentSecurityDescriptorId] FOREIGN KEY ([ParentSecurityDescriptorId]) REFERENCES [dspAuth].[SecurityDescriptor] ([SecurityDescriptorId])
GO
ALTER TABLE [dspAuth].[SecurityDescriptorParent] ADD CONSTRAINT [FK_SecurityDescriptorInheritance_SecurityDescriptor_SecurityDescriptorId] FOREIGN KEY ([SecurityDescriptorId]) REFERENCES [dspAuth].[SecurityDescriptor] ([SecurityDescriptorId]) ON DELETE CASCADE
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'139', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorParent', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorParent', NULL, NULL
GO
