/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[SecurityDescriptorRolePermission]
(
[SecurityDescriptorId] [bigint] NOT NULL,
[RoleId] [int] NOT NULL,
[PermissionGroupId] [smallint] NOT NULL,
[AuditUserId] [int] NOT NULL
)
GO
ALTER TABLE [dspAuth].[SecurityDescriptorRolePermission] ADD CONSTRAINT [PK_SecurityDescriptorRolePermission] PRIMARY KEY CLUSTERED  ([SecurityDescriptorId], [RoleId], [PermissionGroupId])
GO
ALTER TABLE [dspAuth].[SecurityDescriptorRolePermission] ADD CONSTRAINT [FK_SecurityDescriptorRolePermission_PermissionGroup_PermissionGroupId] FOREIGN KEY ([PermissionGroupId]) REFERENCES [dspAuth].[PermissionGroup] ([PermissionGroupId])
GO
ALTER TABLE [dspAuth].[SecurityDescriptorRolePermission] ADD CONSTRAINT [FK_SecurityDescriptorRolePermission_Role_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dspAuth].[Role] ([RoleId]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dspAuth].[SecurityDescriptorRolePermission] ADD CONSTRAINT [FK_SecurityDescriptorRolePermission_SecurityDescriptor_SecurityDescriptorId] FOREIGN KEY ([SecurityDescriptorId]) REFERENCES [dspAuth].[SecurityDescriptor] ([SecurityDescriptorId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'140', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorRolePermission', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorRolePermission', NULL, NULL
GO
