/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspAuth].[SecurityDescriptorUserPermission]
(
[SecurityDescriptorId] [bigint] NOT NULL,
[UserId] [int] NOT NULL,
[PermissionGroupId] [smallint] NOT NULL,
[CreatedByUserId] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_SecurityDescriptorUserPermission_CreatedTime] DEFAULT (getdate()),
[ModifiedByUserId] [int] NULL,
[ModifiedTime] [datetime] NULL
)
GO
ALTER TABLE [dspAuth].[SecurityDescriptorUserPermission] ADD CONSTRAINT [PK_SecurityDescriptorUserPermission] PRIMARY KEY CLUSTERED  ([SecurityDescriptorId], [PermissionGroupId], [UserId])
GO
ALTER TABLE [dspAuth].[SecurityDescriptorUserPermission] ADD CONSTRAINT [FK_SecurityDescriptorUserPermission_PermissionGroup_PermissionGroupId] FOREIGN KEY ([PermissionGroupId]) REFERENCES [dspAuth].[PermissionGroup] ([PermissionGroupId])
GO
EXEC sp_addextendedproperty N'DatabaseVersioningPriorityLevel', N'145', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorUserPermission', NULL, NULL
GO
EXEC sp_addextendedproperty N'TemporalTypeId', N'1', 'SCHEMA', N'dspAuth', 'TABLE', N'SecurityDescriptorUserPermission', NULL, NULL
GO
