/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [DatabaseVersioning].[Setting]
(
[Id] [int] NOT NULL,
[GetDataRowCount] [int] NOT NULL CONSTRAINT [DF_Setting_IsFeatureEnabled] DEFAULT ((1000)),
[MirroringIsEnabled] [bit] NOT NULL CONSTRAINT [DF_Setting_MirroringIsEnabled] DEFAULT ((0))
)
GO
ALTER TABLE [DatabaseVersioning].[Setting] ADD CONSTRAINT [PK_Setting_1] PRIMARY KEY CLUSTERED  ([Id])
GO
