/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[tSQLt].[AssertStringTable]') IS NOT NULL
	DROP TYPE [tSQLt].[AssertStringTable];

GO
CREATE TYPE [tSQLt].[AssertStringTable] AS TABLE
(
[value] [nvarchar] (max) NULL
)
GO
