/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [tSQLt].[Private_NewTestClassList]
(
[ClassName] [nvarchar] (450) NOT NULL
)
GO
ALTER TABLE [tSQLt].[Private_NewTestClassList] ADD CONSTRAINT [PK__Private___F8BF561A3B975135] PRIMARY KEY CLUSTERED  ([ClassName])
GO
