/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [tSQLt].[Private_AssertEqualsTableSchema_Actual]
(
[name] [nvarchar] (256) NULL,
[RANK(column_id)] [int] NULL,
[system_type_id] [nvarchar] (max) NULL,
[user_type_id] [nvarchar] (max) NULL,
[max_length] [smallint] NULL,
[precision] [tinyint] NULL,
[scale] [tinyint] NULL,
[collation_name] [nvarchar] (256) NULL,
[is_nullable] [bit] NULL,
[is_identity] [bit] NULL
)
GO
