/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [tSQLt].[Run_LastExecution]
(
[TestName] [nvarchar] (max) NULL,
[SessionId] [int] NULL,
[LoginTime] [datetime] NULL
)
GO
