IF OBJECT_ID('[tSQLt].[Reset]') IS NOT NULL
	DROP PROCEDURE [tSQLt].[Reset];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [tSQLt].[Reset]
AS
BEGIN
  EXEC tSQLt.Private_ResetNewTestClassList;
END;
GO
