IF OBJECT_ID('[dspconst].[ProviderType_Email]') IS NOT NULL
	DROP FUNCTION [dspconst].[ProviderType_Email];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE  FUNCTION [dspconst].[ProviderType_Email] ()
RETURNS TINYINT
WITH SCHEMABINDING
AS
BEGIN
    RETURN 3;
END;
GO
