IF OBJECT_ID('[dspconst].[ProviderType_SMS]') IS NOT NULL
	DROP FUNCTION [dspconst].[ProviderType_SMS];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE  FUNCTION [dspconst].[ProviderType_SMS] ()
RETURNS TINYINT
WITH SCHEMABINDING
AS
BEGIN
    RETURN 1;
END;
GO
