/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE SCHEMA [api]
AUTHORIZATION [dbo]
GO
GRANT EXECUTE ON SCHEMA:: [api] TO [ApiCallers]
GO
EXEC sp_addextendedproperty N'InvokerApi', N'1', 'SCHEMA', N'api', NULL, NULL, NULL, NULL
GO
