/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[InboxMessage]
(
[InboxMessageId] [bigint] NOT NULL IDENTITY(1, 1),
[MessageRefrenceNumber] [nvarchar] (50) NULL,
[Address] [nvarchar] (500) NOT NULL,
[MessageBody] [nvarchar] (1000) NOT NULL,
[MessageTime] [datetime] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_InboxProc_CreatedTime_Default] DEFAULT (getdate()),
[MessagePatternId] [int] NULL,
[ProviderInfoId] [int] NOT NULL,
[MessageServerCreatedTime] [datetime] NOT NULL,
[MessageServerInboxNumber] [bigint] NOT NULL,
[InboxMessageProcessStateId] [tinyint] NOT NULL,
[ProcessStartTime] [datetime] NULL,
[ProcessEndTime] [datetime] NULL,
[Error] [nvarchar] (4000) NULL
)
GO
ALTER TABLE [dspInboxMessage].[InboxMessage] ADD CONSTRAINT [PK_InboxProcessedMessage] PRIMARY KEY CLUSTERED  ([InboxMessageId])
GO
CREATE NONCLUSTERED INDEX [IX_Address_InboxMessageProcessStateId5] ON [dspInboxMessage].[InboxMessage] ([Address]) WHERE ([InboxMessageProcessStateId]=(5))
GO
CREATE NONCLUSTERED INDEX [IX_AddressMessageTime_InboxMessageProcessStateId1] ON [dspInboxMessage].[InboxMessage] ([Address]) WHERE ([InboxMessageProcessStateId]=(1))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MessageServerInboxId] ON [dspInboxMessage].[InboxMessage] ([MessageServerInboxNumber])
GO
ALTER TABLE [dspInboxMessage].[InboxMessage] ADD CONSTRAINT [FK_InboxMessage_ProviderInfo] FOREIGN KEY ([ProviderInfoId]) REFERENCES [dspInboxMessage].[ProviderInfo] ([ProviderInfoId])
GO
ALTER TABLE [dspInboxMessage].[InboxMessage] ADD CONSTRAINT [FK_InboxProcessedMessage_MessagePattern1] FOREIGN KEY ([MessagePatternId]) REFERENCES [dspInboxMessage].[MessagePattern] ([MessagePatternId])
GO
ALTER TABLE [dspInboxMessage].[InboxMessage] ADD CONSTRAINT [FK_InboxProcessedMessage_ProcessState] FOREIGN KEY ([InboxMessageProcessStateId]) REFERENCES [dspInboxMessage].[InboxMessageProcessState] ([InboxMessageProcessStateId])
GO
