/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[InboxMessageProcessState]
(
[InboxMessageProcessStateId] [tinyint] NOT NULL,
[InboxMessageProcessState] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dspInboxMessage].[InboxMessageProcessState] ADD CONSTRAINT [PK_ProcessState] PRIMARY KEY CLUSTERED  ([InboxMessageProcessStateId])
GO
