/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[MessagePattern]
(
[MessagePatternId] [int] NOT NULL IDENTITY(1, 1),
[PatternName] [nvarchar] (200) NOT NULL,
[StartTime] [datetime] NOT NULL,
[ExpirationTime] [datetime] NOT NULL,
[MessagePatternSepratorId] [int] NOT NULL,
[PatternKey] [nvarchar] (200) NOT NULL,
[MessagePatternStateId] [int] NOT NULL,
[ResponseProcedureSchemaName] [nvarchar] (50) NOT NULL,
[ResponseProcedureName] [nvarchar] (1000) NOT NULL,
[IsDeleted] [bit] NOT NULL CONSTRAINT [DF_MessagePattern_IsDeleted] DEFAULT ((0)),
[Description] [nvarchar] (max) NULL
)
GO
ALTER TABLE [dspInboxMessage].[MessagePattern] ADD CONSTRAINT [PK_MessagePattern] PRIMARY KEY CLUSTERED  ([MessagePatternId])
GO
ALTER TABLE [dspInboxMessage].[MessagePattern] ADD CONSTRAINT [FK_MessagePattern_MessagePatternSeprator] FOREIGN KEY ([MessagePatternSepratorId]) REFERENCES [dspInboxMessage].[MessagePatternSeprator] ([MessagePatternSepratorId])
GO
ALTER TABLE [dspInboxMessage].[MessagePattern] ADD CONSTRAINT [FK_MessagePattern_MessagePatternState] FOREIGN KEY ([MessagePatternStateId]) REFERENCES [dspInboxMessage].[MessagePatternState] ([MessagePatternStateId])
GO
