/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[MessagePatternSeprator]
(
[MessagePatternSepratorId] [int] NOT NULL,
[MessagePatternSeprator] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dspInboxMessage].[MessagePatternSeprator] ADD CONSTRAINT [PK_MessagePatternSeprator] PRIMARY KEY CLUSTERED  ([MessagePatternSepratorId])
GO
