/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[MessagePatternStepType]
(
[MessagePatternStepTypeId] [tinyint] NOT NULL,
[MessagePatternStepType] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dspInboxMessage].[MessagePatternStepType] ADD CONSTRAINT [PK_MessagePatternStepType] PRIMARY KEY CLUSTERED  ([MessagePatternStepTypeId])
GO
