/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[MessagePatternStep]
(
[MessagePatternStepId] [int] NOT NULL IDENTITY(1, 1),
[MessagePatternId] [int] NOT NULL,
[MessagePatternStepTypeId] [tinyint] NOT NULL,
[ParameterName] [nvarchar] (300) NULL,
[SendMessageValue] [nvarchar] (4000) NULL,
[Order] [int] NOT NULL,
[DefaultValue] [nvarchar] (4000) NULL,
[Description] [nvarchar] (max) NULL,
[ConfirmHasCustomValidation] [bit] NULL,
[HasCustomValue] [bit] NULL
)
GO
ALTER TABLE [dspInboxMessage].[MessagePatternStep] ADD CONSTRAINT [PK_MessagePatternSteps] PRIMARY KEY CLUSTERED  ([MessagePatternStepId])
GO
CREATE NONCLUSTERED INDEX [IX_MessagePatternStep_MessagePatternId] ON [dspInboxMessage].[MessagePatternStep] ([MessagePatternId]) INCLUDE ([Order])
GO
ALTER TABLE [dspInboxMessage].[MessagePatternStep] ADD CONSTRAINT [FK_MessagePatternSteps_MessagePattern] FOREIGN KEY ([MessagePatternId]) REFERENCES [dspInboxMessage].[MessagePattern] ([MessagePatternId])
GO
ALTER TABLE [dspInboxMessage].[MessagePatternStep] ADD CONSTRAINT [FK_MessagePatternSteps_MessagePatternStepType] FOREIGN KEY ([MessagePatternStepTypeId]) REFERENCES [dspInboxMessage].[MessagePatternStepType] ([MessagePatternStepTypeId])
GO
