/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[ProviderType]
(
[ProviderTypeId] [tinyint] NOT NULL,
[ProviderType] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dspInboxMessage].[ProviderType] ADD CONSTRAINT [PK_ProviderType] PRIMARY KEY CLUSTERED  ([ProviderTypeId])
GO
