/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[WaitForReplyMessageState]
(
[WaitForReplyMessageStateId] [tinyint] NOT NULL,
[WaitForReplyMessageState] [nvarchar] (50) NOT NULL
)
GO
ALTER TABLE [dspInboxMessage].[WaitForReplyMessageState] ADD CONSTRAINT [PK_WaitForReplyMessageState] PRIMARY KEY CLUSTERED  ([WaitForReplyMessageStateId])
GO
