/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dspInboxMessage].[WaitForReplyMessage]
(
[WaitForReplyMessageId] [bigint] NOT NULL IDENTITY(1, 1),
[Address] [nvarchar] (100) NULL,
[MessagePatternStepId] [int] NULL,
[MessageLastData] [nvarchar] (max) NULL,
[WaitForReplyMessageStateId] [tinyint] NOT NULL CONSTRAINT [DF__WaitForRe__IsPro__4203A4B5] DEFAULT ((0)),
[ProviderInfoId] [int] NOT NULL,
[CreatedTime] [datetime] NOT NULL CONSTRAINT [DF_WaitForReplyMessage_CreatedTime] DEFAULT (getdate())
)
GO
ALTER TABLE [dspInboxMessage].[WaitForReplyMessage] ADD CONSTRAINT [PK_WaitForReplyMessage] PRIMARY KEY CLUSTERED  ([WaitForReplyMessageId])
GO
CREATE NONCLUSTERED INDEX [IX_AddressProviderInfoId] ON [dspInboxMessage].[WaitForReplyMessage] ([Address], [ProviderInfoId]) INCLUDE ([CreatedTime]) WHERE ([WaitForReplyMessageStateId]=(3))
GO
ALTER TABLE [dspInboxMessage].[WaitForReplyMessage] ADD CONSTRAINT [FK_WaitForReplyMessage_WaitForReplyMessageState] FOREIGN KEY ([WaitForReplyMessageStateId]) REFERENCES [dspInboxMessage].[WaitForReplyMessageState] ([WaitForReplyMessageStateId])
GO
