IF OBJECT_ID('[err].[AuthUserNotFoundId]') IS NOT NULL
	DROP FUNCTION [err].[AuthUserNotFoundId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[AuthUserNotFoundId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55025;  
END
GO
