IF OBJECT_ID('[err].[BatchIsNotAllowedId]') IS NOT NULL
	DROP FUNCTION [err].[BatchIsNotAllowedId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[BatchIsNotAllowedId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55023;  
END
GO
