IF OBJECT_ID('[err].[InvalidArgumentId]') IS NOT NULL
	DROP FUNCTION [err].[InvalidArgumentId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[InvalidArgumentId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55011;  
END
GO
