IF OBJECT_ID('[err].[InvalidCaptchaId]') IS NOT NULL
	DROP FUNCTION [err].[InvalidCaptchaId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[InvalidCaptchaId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55022;  
END
GO
