IF OBJECT_ID('[err].[InvalidOperationId]') IS NOT NULL
	DROP FUNCTION [err].[InvalidOperationId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[InvalidOperationId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55016;  
END
GO
