IF OBJECT_ID('[err].[LockFailedId]') IS NOT NULL
	DROP FUNCTION [err].[LockFailedId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[LockFailedId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55013;  
END
GO
