IF OBJECT_ID('[err].[MaintenanceReadOnlyId]') IS NOT NULL
	DROP FUNCTION [err].[MaintenanceReadOnlyId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[MaintenanceReadOnlyId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55028;  
END
GO
