IF OBJECT_ID('[err].[MaintenanceId]') IS NOT NULL
	DROP FUNCTION [err].[MaintenanceId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[MaintenanceId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55027;  
END
GO
