IF OBJECT_ID('[err].[NoOperationId]') IS NOT NULL
	DROP FUNCTION [err].[NoOperationId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[NoOperationId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55021;  
END
GO
