IF OBJECT_ID('[err].[NotImplemetedId]') IS NOT NULL
	DROP FUNCTION [err].[NotImplemetedId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[NotImplemetedId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55018;  
END
GO
