IF OBJECT_ID('[err].[NotSupportedId]') IS NOT NULL
	DROP FUNCTION [err].[NotSupportedId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[NotSupportedId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55017;  
END
GO
