IF OBJECT_ID('[err].[ObjectAlreadyExistsId]') IS NOT NULL
	DROP FUNCTION [err].[ObjectAlreadyExistsId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[ObjectAlreadyExistsId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55004;  
END
GO
