IF OBJECT_ID('[err].[PageSizeTooLargeId]') IS NOT NULL
	DROP FUNCTION [err].[PageSizeTooLargeId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[PageSizeTooLargeId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55009;  
END
GO
