IF OBJECT_ID('[err].[TooManyRequestId]') IS NOT NULL
	DROP FUNCTION [err].[TooManyRequestId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[TooManyRequestId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55024;  
END
GO
