IF OBJECT_ID('[err].[UserIsDisabledId]') IS NOT NULL
	DROP FUNCTION [err].[UserIsDisabledId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [err].[UserIsDisabledId]()
RETURNS INT WITH SCHEMABINDING
AS
BEGIN
	RETURN 55019;  
END
GO
