IF OBJECT_ID('[dsp].[Const_Algorithm_PBKDF2_SHA512]') IS NOT NULL
	DROP FUNCTION [dsp].[Const_Algorithm_PBKDF2_SHA512];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dsp].[Const_Algorithm_PBKDF2_SHA512] ( )
RETURNS TSTRING
AS
BEGIN
    RETURN 'PBKDF2_SHA512';
END;


GO
