IF OBJECT_ID('[dsp].[DateTime_ConvertLocalToUTC]') IS NOT NULL
	DROP FUNCTION [dsp].[DateTime_ConvertLocalToUTC];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE   FUNCTION [dsp].[DateTime_ConvertLocalToUTC] (@LocalDate DATETIME)
RETURNS DATETIME2
WITH SCHEMABINDING
AS
BEGIN

    RETURN DATEADD(MINUTE, -DATEDIFF(MINUTE, GETUTCDATE(), GETDATE()), @LocalDate);

END;
GO
