IF OBJECT_ID('[dsp].[DateTime_EndOfDayTime]') IS NOT NULL
	DROP FUNCTION [dsp].[DateTime_EndOfDayTime];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dsp].[DateTime_EndOfDayTime] (
	@Time DATETIME)
RETURNS DATETIME
AS
BEGIN
	DECLARE @NextDay DATETIME = DATEADD(DAY, 1, CAST(CAST(@Time AS DATE) AS DATETIME));
	SET @Time = DATEADD(MILLISECOND, -10, @NextDay);

	RETURN @Time;
END;

GO
