IF OBJECT_ID('[dsp].[Table_GetPrimaryKey]') IS NOT NULL
	DROP FUNCTION [dsp].[Table_GetPrimaryKey];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dsp].[Table_GetPrimaryKey] (@Schemaname TSTRING,
    @TableName TSTRING)
RETURNS TSTRING
AS
BEGIN
    RETURN (   SELECT   KU.COLUMN_NAME AS PrimaryColumn
                 FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
                        INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU ON --
                        TC.CONSTRAINT_TYPE = 'PRIMARY KEY' AND  TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME AND KU.TABLE_NAME = @TableName);
END;




GO
