/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF OBJECT_ID('[syn].[MessageServer_InboxMessageList]') IS NOT NULL
	DROP SYNONYM [syn].[MessageServer_InboxMessageList];

GO
CREATE SYNONYM [syn].[MessageServer_InboxMessageList] FOR [IcMessage].[api].[InboxMessage_List]
GO
