IF OBJECT_ID('[dsperr].[GeneralExceptionId]') IS NOT NULL
	DROP FUNCTION [dsperr].[GeneralExceptionId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[GeneralExceptionId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55026;  
END
			
GO
