IF OBJECT_ID('[dsperr].[HasNotSameStrcutreId]') IS NOT NULL
	DROP FUNCTION [dsperr].[HasNotSameStrcutreId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[HasNotSameStrcutreId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55025;  
END
			
GO
