IF OBJECT_ID('[dsperr].[NotImplemetedId]') IS NOT NULL
	DROP FUNCTION [dsperr].[NotImplemetedId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[NotImplemetedId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55012;  
END
			
GO
