IF OBJECT_ID('[dsperr].[PageSizeTooLargeId]') IS NOT NULL
	DROP FUNCTION [dsperr].[PageSizeTooLargeId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[PageSizeTooLargeId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55005;  
END
			
GO
