IF OBJECT_ID('[dsperr].[TooManyRequestId]') IS NOT NULL
	DROP FUNCTION [dsperr].[TooManyRequestId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[TooManyRequestId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55018;  
END
			
GO
