IF OBJECT_ID('[dsperr].[UserIsDisabledId]') IS NOT NULL
	DROP FUNCTION [dsperr].[UserIsDisabledId];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE FUNCTION [dsperr].[UserIsDisabledId]()
RETURNS INT 
WITH SCHEMABINDING
AS
BEGIN
	RETURN 55013;  
END
			
GO
